version: "3.9"
services:
  postgres:
    container_name: task
    image: postgres
    environment:
      POSTGRES_DB: "task"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"